; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!


;*************************************************************************************
;
;                  DO COPY INITIAL hxgrid.ini BEFORE BUILDING RELEASE !
;
;*************************************************************************************

[Setup]
PrivilegesRequired=admin
AppName=hxGrid agent
AppVerName={cm:NameAndVersion}
AppPublisher=Roman Lut
AppPublisherURL=http://www.deep-shadows.com/hax/
AppSupportURL=http://www.deep-shadows.com/hax/
AppUpdatesURL=http://www.deep-shadows.com/hax/
DefaultDirName={pf}\hxGrid
DirExistsWarning=no
DefaultGroupName=hxGrid
AllowNoIcons=yes
OutputBaseFilename=hxgrid_agent_setup
Compression=lzma/max
SolidCompression=yes
AppMutex=hxgridagent

[Languages]
Name: "eng"; MessagesFile: "compiler:Default.isl"
Name: "bra"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "cat"; MessagesFile: "compiler:Languages\Catalan.isl"
Name: "cze"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "dan"; MessagesFile: "compiler:Languages\Danish.isl"
Name: "dut"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "fre"; MessagesFile: "compiler:Languages\French.isl"
Name: "ger"; MessagesFile: "compiler:Languages\German.isl"
Name: "hun"; MessagesFile: "compiler:Languages\Hungarian.isl"
Name: "ita"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "nor"; MessagesFile: "compiler:Languages\Norwegian.isl"
Name: "pol"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "por"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "rus"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "slo"; MessagesFile: "compiler:Languages\Slovenian.isl"

[CustomMessages]
NameAndVersion=hxGrid agent 1.09d

Note1=Note: other options can be changed in agent.ini file.
rus.Note1=Примечание: другие параметры можно изменить в файле agent.ini.

Text1=Coordinator address
rus.Text1=Адрес Координатора

Text2=Coordinator machine IP address
rus.Text2=Сетевой адрес Координатора

Text3=Coordinator machine IP address [xxx.xxx.xxx.xxx]:
rus.Text3=Укажите IP адрес машины-координатора [xxx.xxx.xxx.xxx]:

[Files]
Source: "D:\_Research\hxgrid\Agent\bin\agent.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\_Research\hxgrid\Agent\bin\zlib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\_Research\hxgrid\Agent\bin\hxgrid.ini"; DestDir: "{app}"; Flags: ignoreversion confirmoverwrite uninsneveruninstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Agent\{cm:NameAndVersion}"; Filename: "{app}\agent.exe"
Name: "{group}\hxgrid.ini"; Filename: "{app}\hxgrid.ini"
Name: "{group}\Agent\{cm:UninstallProgram,hxGrid agent}"; Filename: "{uninstallexe}"
Name: "{commonstartup}\{cm:NameAndVersion}"; Filename: "{app}\agent.exe"

[Run]
Filename: "{app}\agent.exe"; Description: "{cm:LaunchProgram,{cm:NameAndVersion}}"; Flags: nowait postinstall skipifsilent

;[INI]
;Filename: "{app}\agent.ini"; Section: "settings"; Key: "coordinator_ip"; String: "{code:GetCoordinatorIp}"

[UninstallDelete]
Type: filesandordirs; Name: "{app}\temp"


[code]

var
  Page: TWizardPage;
  StaticText1, StaticText2: TNewStaticText;
  Edit1: TEdit;


procedure InitializeWizard();
var
 s: string;
begin
exit;
  { TButton and others }

  Page := CreateCustomPage(wpSelectDir, ExpandConstant('{cm:Text1}'), ExpandConstant('{cm:Text2}'));

  StaticText1 := TNewStaticText.Create(Page);
  StaticText1.Caption := ExpandConstant('{cm:Text3}');
  StaticText1.AutoSize := True;
  StaticText1.Parent := Page.Surface;

  Edit1 := TEdit.Create(Page);
  Edit1.Top := StaticText1.Top + StaticText1.Height + ScaleY(4);
  Edit1.Width := Page.SurfaceWidth - ScaleX(8);
  Edit1.Parent := Page.Surface;
  Edit1.Text := '192.168.0.1';

  StaticText2 := TNewStaticText.Create(Page);
  StaticText2.Caption := ExpandConstant('{cm:Note1}');
  StaticText2.AutoSize := True;
  StaticText2.Parent := Page.Surface;
  StaticText2.Top := Edit1.Top + Edit1.Height + ScaleY(10);

end;

function GetCoordinatorIp(s:string): string;
begin
 result:=trim(edit1.text);
end;
